### PR TITLE
Set the Access-Control-Allow-Credentials header to allow cookies to be sent

### PR DESCRIPTION
**Pull request by alexjfno1**

### CODE REVIEW

**Comment by ldabiralai** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :tada: Your code is formatted correctly
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by ldabiralai** [comment]
Did you forget to push the code?

Looks like this is just updated dependencies, unless I'm missing something!

**Comment by alexjfno1** [comment]
@ldabiralai Not quite finished yet, only opened the PR to get CircleCi to run.

**Comment by alexjfno1** [comment]
@ldabiralai All good to review. I just want to test in an app first before merging to make sure it works.

**Pull request merged**
