### PR TITLE
add requestHeaders

### PR DESCRIPTION
**Pull request by NowTV-Assurance**
- added options.requestHeaders which will check if a request has matching headers before responding
- added tests in responseTest and homepageTest
- updated ReadMe.md
- removed travis in favour of CircleCI

also added a `.editorconfig` as the pages had a mix of 2 spaces and 4... which has affected this PR

### CODE REVIEW

**Comment by ldabiralai** [comment]
Thanks for this.

I don’t agree that we should be importing lodash, all we’re using it for is to convert headers to lowercase, and also as headers are case-insensitive we should not be worrying about this.
It’s up to the consumer to make sure that their mock and what they’re expecting is the same case, if it’s an issue for them.

If you could remove lodash and the .toLowerCase on the headers in both places then I’d be happy to merge this in.

**Comment by peter-mouland** [comment]
When we setup an uppercase header in simulado, the requests are made through superagent, the headers are then lowerCase, other tools can behave similarly.  This is why we convert to lowercase, so that they match.  Removing this will break the functionality.

Lodash has been updated to simply use the mapkeys file/function.

**Comment by ldabiralai** [comment]
If I'm mocking an enpoint using simulado, I should get back from simulado whatever I put into it, when looking at it through the browser. If I mock `X-Account-Number` then I should get back `X-Account-Number`. If I mock `x-account-number` I should get `x-account-number`.

If superagent wants to convert the headers it returns to lowercase then that is not a problem, but we should not be changing what the user expects to be returned when they know what they've mocked it with.

**Comment by ldabiralai** [comment]
Going to close this PR as it's not going to be merged. But I'm going to try and get around to reimplementing it when I have some time.

**Pull request closed without merging**
